/**
 * Generates one CSF file per host story (app/stories/imgui/<id>.stories.ts) from
 * `host --list --json`. Presets become additional named stories.
 */
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { runHost, paths } from './lib/host.mjs';

const outDir = path.join(paths.root, 'app', 'stories', 'imgui');

function argTypeControl(arg) {
  switch (arg.type) {
    case 'STRING':
      return `{ control: 'text' }`;
    case 'BOOLEAN':
      return `{ control: 'boolean' }`;
    case 'INT':
      return `{ control: { type: 'number', step: 1 } }`;
    case 'FLOAT':
      return `{ control: { type: 'number', step: 0.1 } }`;
    case 'ENUM':
      return `{ control: 'select', options: ${JSON.stringify(arg.options ?? [])} }`;
    case 'COLOR':
      return `{ control: 'color' }`;
    default:
      return `{ control: 'text' }`;
  }
}

function literal(value) {
  return JSON.stringify(value);
}

function pascalCase(name) {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

function storyFile(story) {
  const defaults = story.args.map((arg) => `  ${JSON.stringify(arg.name)}: ${literal(arg.default)}`);
  const argTypes = story.args.map((arg) => `  ${JSON.stringify(arg.name)}: ${argTypeControl(arg)}`);

  const presetExports = Object.entries(story.presets ?? {})
    .filter(([name]) => pascalCase(name).toLowerCase() !== 'default')
    .map(([name, values]) => {
      const merged = {};
      for (const arg of story.args) merged[arg.name] = arg.default;
      Object.assign(merged, values);
      const argsLines = Object.entries(merged).map(
        ([key, value]) => `    ${JSON.stringify(key)}: ${literal(value)}`,
      );
      return `export const ${pascalCase(name)}: StoryObj = {\n  args: {\n${argsLines.join(',\n')}\n  }\n};`;
    })
    .join('\n\n');

  return `// AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
// Source: ${story.storyClass}
import type { Meta, StoryObj } from '@storybook/html-vite';
import { mountImGuiStory } from '@imgui-storybook/client';

const meta = {
  title: ${literal(`ImGui/${story.title}`)},
  render: (args: any, ctx: any) =>
    mountImGuiStory({
      storyId: ${literal(story.id)},
      args,
      globals: ctx.globals,
      description: ${literal(story.description)},
      presets: ${JSON.stringify(story.presets ?? {})},
    }),
  args: {
${defaults.join(',\n')}
  },
  argTypes: {
${argTypes.join(',\n')}
  },
  parameters: {
    imgui: {
      storyId: ${literal(story.id)},
      storyClass: ${literal(story.storyClass)},
    },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj = {};
${presetExports ? `\n${presetExports}\n` : ''}`;
}

async function main() {
  console.log('[gen] asking host for the story catalog...');
  const catalogJson = await runHost(['--list', '--json']);
  const catalog = JSON.parse(catalogJson);
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  let presets = 0;
  for (const story of catalog.stories) {
    const file = path.join(outDir, `${story.id}.stories.ts`);
    await writeFile(file, storyFile(story), 'utf8');
    presets += Object.keys(story.presets ?? {}).length;
  }
  console.log(
    `[gen] wrote ${catalog.stories.length} story files (${presets} presets) to ${path.relative(paths.root, outDir)}`,
  );
  console.log(`[gen] host ${catalog.hostVersion} · binding ${catalog.imguiJavaVersion} · Dear ImGui ${catalog.dearImgui}`);
  const leftovers = await readdir(path.dirname(outDir));
  console.log(`[gen] stories dir now: ${leftovers.join(', ')}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
